/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vista.grafoEjemplo;

import controlador.tda.grafos.Grafo;
import controlador.tda.grafos.GrafoD;
import controlador.tda.grafos.GrafoND;
import javax.swing.JOptionPane;
import vista.grafoEjemplo.modelo.ModeloTablaGrafo;

/**
 *
 * @author sebastian
 */
public class FrmGrafo extends javax.swing.JDialog {

    private Grafo gd;
    private ModeloTablaGrafo mt = new ModeloTablaGrafo();

    /**
     * Creates new form FrmGrafo
     */
    public FrmGrafo(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        buttonGroup1.add(radioGD);
        buttonGroup1.add(radioGND);
        radioGD.setSelected(true);
        jPanel4.setVisible(false);
    }

    private void generarGrafo() {
        Integer v = Integer.parseInt(cbx_vertices.getSelectedItem().toString());
        if (radioGD.isSelected()) {
            this.gd = new GrafoD(v);
        } else {
            this.gd = new GrafoND(v);
        }

        cbx_origen.removeAllItems();
        cbx_destino.removeAllItems();
        for (int i = 1; i <= v; i++) {
            cbx_origen.addItem(String.valueOf(i));
            cbx_destino.addItem(String.valueOf(i));
        }
        //System.out.println(this.gd.toString());
        cargarTabla();
        jPanel4.setVisible(true);
    }

    private void cargarTabla() {
        mt.setGrafo(gd);
        tbltabla.setModel(mt);
        mt.fireTableStructureChanged();
        tbltabla.updateUI();
    }

    private void adyacencias() {
        try {
            Double peso = Double.parseDouble(txtpeso.getText());
            Integer i = Integer.parseInt(cbx_origen.getSelectedItem().toString());
            Integer f = Integer.parseInt(cbx_destino.getSelectedItem().toString());
            if (i == f) {
                JOptionPane.showMessageDialog(null, "Vertices iguales", "ERROR", JOptionPane.ERROR_MESSAGE);
            } else {
                try {
                    gd.insertarArista(i, f, peso);
                    cargarTabla();
                } catch (Exception e) {
                    System.out.println("Error en adyacencias " + e);
                    JOptionPane.showMessageDialog(null, "NO SE PUEDE INSERTAR", "ERROR", JOptionPane.ERROR_MESSAGE);
                }
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "NO SE PUEDE INSERTAR "+e.toString().toUpperCase(), "ERROR", JOptionPane.ERROR_MESSAGE);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        cbx_vertices = new javax.swing.JComboBox<>();
        btnGenerar = new javax.swing.JButton();
        radioGD = new javax.swing.JRadioButton();
        radioGND = new javax.swing.JRadioButton();
        jPanel3 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        cbx_origen = new javax.swing.JComboBox<>();
        jLabel3 = new javax.swing.JLabel();
        cbx_destino = new javax.swing.JComboBox<>();
        btnOk = new javax.swing.JButton();
        txtpeso = new javax.swing.JTextField();
        jPanel4 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbltabla = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        getContentPane().setLayout(null);

        jPanel1.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel1.setLayout(null);

        jPanel2.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel2.setLayout(null);

        jLabel1.setText("Nro de vertices");
        jPanel2.add(jLabel1);
        jLabel1.setBounds(20, 20, 120, 16);

        cbx_vertices.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "4", "5", "6", "7", "8", "9", "10" }));
        jPanel2.add(cbx_vertices);
        cbx_vertices.setBounds(140, 10, 72, 22);

        btnGenerar.setText("GENERAR");
        btnGenerar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGenerarActionPerformed(evt);
            }
        });
        jPanel2.add(btnGenerar);
        btnGenerar.setBounds(270, 10, 120, 22);

        radioGD.setText("GD");
        jPanel2.add(radioGD);
        radioGD.setBounds(410, 20, 60, 20);

        radioGND.setText("GND");
        jPanel2.add(radioGND);
        radioGND.setBounds(550, 20, 70, 20);

        jPanel1.add(jPanel2);
        jPanel2.setBounds(10, 10, 720, 70);

        jPanel3.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel3.setLayout(null);

        jLabel2.setText("Vert Origen");
        jPanel3.add(jLabel2);
        jLabel2.setBounds(20, 20, 100, 16);

        cbx_origen.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "0" }));
        jPanel3.add(cbx_origen);
        cbx_origen.setBounds(110, 10, 80, 22);

        jLabel3.setText("Vert Destino");
        jPanel3.add(jLabel3);
        jLabel3.setBounds(230, 20, 100, 16);

        cbx_destino.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "0" }));
        jPanel3.add(cbx_destino);
        cbx_destino.setBounds(350, 10, 80, 22);

        btnOk.setText("OK");
        btnOk.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnOkActionPerformed(evt);
            }
        });
        jPanel3.add(btnOk);
        btnOk.setBounds(590, 20, 110, 22);
        jPanel3.add(txtpeso);
        txtpeso.setBounds(450, 10, 120, 22);

        jPanel1.add(jPanel3);
        jPanel3.setBounds(10, 90, 720, 60);

        jPanel4.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel4.setLayout(null);

        tbltabla.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tbltabla);

        jPanel4.add(jScrollPane1);
        jScrollPane1.setBounds(20, 20, 690, 160);

        jButton1.setText("MOSTRAR");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel4.add(jButton1);
        jButton1.setBounds(300, 190, 130, 22);

        jPanel1.add(jPanel4);
        jPanel4.setBounds(10, 160, 720, 240);

        getContentPane().add(jPanel1);
        jPanel1.setBounds(0, 0, 750, 410);

        setSize(new java.awt.Dimension(756, 447));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnGenerarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGenerarActionPerformed
        // TODO add your handling code here:
        generarGrafo();
    }//GEN-LAST:event_btnGenerarActionPerformed

    private void btnOkActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnOkActionPerformed
        // TODO add your handling code here:
        adyacencias();
    }//GEN-LAST:event_btnOkActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        FrmGrafoVista frm = new FrmGrafoVista(gd);
        frm.setSize(400, 400);
        frm.setVisible(true);
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmGrafo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmGrafo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmGrafo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmGrafo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                FrmGrafo dialog = new FrmGrafo(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnGenerar;
    private javax.swing.JButton btnOk;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JComboBox<String> cbx_destino;
    private javax.swing.JComboBox<String> cbx_origen;
    private javax.swing.JComboBox<String> cbx_vertices;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JRadioButton radioGD;
    private javax.swing.JRadioButton radioGND;
    private javax.swing.JTable tbltabla;
    private javax.swing.JTextField txtpeso;
    // End of variables declaration//GEN-END:variables
}
